// src/views/main/job-summary/JobSummary.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import {
  ArrowLeft,
  CheckCircle2,
  Briefcase,
  MapPin,
  Map,
  Car,
  Clock,
  IndianRupee,
  Shield,
  Utensils,
  Gift,
  Home,
  Gauge,
  CreditCard,
  Users,
  Calendar,
  Wrench,
  FileText,
  Pencil,
} from 'lucide-vue-next'
import { useJobStore } from '../../../stores/job'
import { apiPostForm } from '../../../services/config/api'
import { END_POINTS } from '../../../services/config/api'
import JobPremiumModal from '../../../components/JobPremiumModal.vue'
import { cleanupRazorpayOverlay } from '../../../utils/razorpayCleanup'

const props = defineProps<{
  user?: { role?: string; id?: unknown; name?: string; mobile?: string; email?: string } | null
}>()

const emit = defineEmits(['back', 'navigate'])

const jobStore = useJobStore()
const draft = computed(() => jobStore.addJob)
const editingJob = computed(() => jobStore.editingJob)
const submitting = ref(false)
const showSuccess = ref(false)
const postedJobId = ref<string | null>(null)
const jobPremiumVisible = ref(false)

const notProvided = 'Not Provided'

// Helpers (mirror AddJob)
const toYesNo = (v: boolean | null) => (v === true ? 'yes' : 'no')
const expToApi = (s: string) => s.replace(/\s*years?\s*/gi, '').replace('-', '-') || s
const licenseToApi = (s: string) => {
  if (s.includes('LMV')) return 'LMV'
  if (s.includes('HMV')) return 'HMV'
  if (s.includes('HGMV')) return 'HGMV'
  if (s.includes('HPMV') || s.includes('HTV')) return 'HPMV/HTV'
  return s
}
const conditionToApi = (s: string) => {
  const m: Record<string, string> = {
    Excellent: 'excellent',
    Good: 'good',
    Average: 'average',
    'Old but running': 'old_running',
    'Made Road Ready': 'road_ready',
  }
  return m[s] || s.toLowerCase().replace(/\s+/g, '_')
}
const vehicleToApi = (s: string) => {
  const m: Record<string, string> = {
    'Trailer/Semi-Trailer': 'Trailer / Semi-Trailer Trucks',
    'Reefer Trucks': 'Refrigerator (Reefer) Trucks',
    'Container Truck': 'Container Trucks',
    'Tipper Trucks': 'Tipper Trucks',
    Tanker: 'Tankers',
  }
  return m[s] || s
}
const formatDeadline = (d: string) => {
  if (!d) return ''
  const [y, m, day] = d.split('-')
  return `${day}-${m}-${y}`
}

const getYesNoValue = (value: boolean | null, desc?: string, suffix?: string) => {
  if (value === true) return desc ? `Yes - ₹${desc}${suffix || '/day'}` : 'Yes'
  if (value === false) return 'No'
  return notProvided
}

const getYesNoValueMileage = (value: boolean | null, desc?: string) => {
  if (value === true) return desc ? `Yes - ${desc} km/l` : 'Yes'
  if (value === false) return 'No'
  return notProvided
}

const deadlineDisplay = computed(() => {
  const d = draft.value?.deadline
  if (!d) return notProvided
  const [y, m, day] = d.split('-')
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const mi = parseInt(m || '1', 10) - 1
  return `${day} ${months[mi]} ${y}`
})

const salaryDisplay = computed(() => {
  const s = draft.value?.salary
  if (!s) return notProvided
  const [a, b] = s.split('-')
  return a && b ? `₹${parseInt(a, 10).toLocaleString()} - ${parseInt(b, 10).toLocaleString()}` : `₹${s}`
})

onMounted(() => {
  if (!draft.value && !editingJob.value) {
    emit('navigate', 'add-job')
  }
})

onBeforeUnmount(() => {
  cleanupRazorpayOverlay()
})

const goBack = () => {
  if (editingJob.value) {
    jobStore.clearEditingJob()
  }
  emit('back')
}

const goEdit = () => {
  if (editingJob.value) {
    jobStore.clearEditingJob()
    emit('back')
  } else {
    emit('back')
  }
}

const submitJob = async () => {
  const d = draft.value
  if (!d) return
  if (!d.consent) {
    alert('Please agree to the consent before posting.')
    return
  }
  submitting.value = true
  try {
    const fd = new FormData()
    fd.append('job_title', d.title)
    fd.append('job_location', d.location)
    fd.append('pincode', d.pincode || '')
    fd.append('area', d.area || '')
    fd.append('route', d.route || '')
    fd.append('vehicle_type', vehicleToApi(d.vehicleType))
    fd.append('Required_Experience', expToApi(d.experience))
    fd.append('Salary_Range', d.salary)
    fd.append('esi_pf', toYesNo(d.hasEsiPf))
    fd.append('food_allowance', toYesNo(d.hasFoodAllowance))
    fd.append('food_allowance_desc', d.foodAllowanceAmount || '')
    fd.append('trip_incentive', toYesNo(d.hasTripIncentive))
    fd.append('trip_incentive_desc', d.tripIncentiveAmount || '')
    fd.append('rahane_ki_suvidha', toYesNo(d.hasAccommodation))
    fd.append('mileage', toYesNo(d.hasMileage))
    fd.append('mileage_desc', d.mileageValue || '')
    fd.append('fast_tag_road_kharcha', toYesNo(d.hasFastag))
    fd.append('fast_tag_road_kharcha_desc', d.fastagAmount || '')
    fd.append('Type_of_License', licenseToApi(d.license))
    fd.append('Preferred_Skills', JSON.stringify(d.skills))
    fd.append('Application_Deadline', formatDeadline(d.deadline))
    fd.append('number_of_drivers_required', d.numberOfDrivers)
    fd.append('Job_Description', d.description)
    fd.append('truck_condition', d.truckCondition ? conditionToApi(d.truckCondition) : '')
    fd.append('consent_visible_driver', d.consent ? '1' : '0')

    const res = await apiPostForm<{ status?: boolean; data?: { unique_id?: string; id?: string }; job_id?: string }>(
      END_POINTS.TRANSPORTER_ADD_JOB,
      fd
    )
    const data = res as { status?: boolean; data?: { unique_id?: string; id?: string }; job_id?: string }
    if (data?.status) {
      const inner = data?.data
      const jobId = inner?.unique_id || inner?.id || data?.job_id || ''
      if (jobId) {
        postedJobId.value = String(jobId)
        jobPremiumVisible.value = true
      } else {
        showSuccess.value = true
        jobStore.clearAddJob()
        setTimeout(() => emit('navigate', 'view-jobs'), 2000)
      }
    } else {
      alert((data as { message?: string })?.message || 'Failed to post job')
    }
  } catch (e) {
    console.error('Add job error:', e)
    alert((e as Error)?.message || 'Something went wrong')
  } finally {
    submitting.value = false
  }
}

const onJobPremiumSuccess = () => {
  jobPremiumVisible.value = false
  showSuccess.value = true
  jobStore.clearAddJob()
  setTimeout(() => emit('navigate', 'view-jobs'), 2000)
}

const onJobPremiumSkip = () => {
  jobPremiumVisible.value = false
  showSuccess.value = true
  jobStore.clearAddJob()
  setTimeout(() => emit('navigate', 'view-jobs'), 2000)
}
</script>

<template>
  <div class="job-summary-wrapper">
    <!-- Header -->
    <div class="dash-header-area">
      <button class="back-btn" @click="goBack" title="Back">
        <ArrowLeft :size="18" />
        <span>Back</span>
      </button>
      <div class="page-title-row">
        <h2 class="page-title">Job Summary</h2>
        <p class="page-subtitle">Review all the details before posting your job</p>
      </div>
    </div>

    <!-- Success State -->
    <div v-if="showSuccess" class="success-block">
      <CheckCircle2 :size="64" color="#10b981" />
      <h2>Job Posted Successfully!</h2>
      <p>Taking you to your jobs...</p>
    </div>

    <!-- Edit Mode: viewing job from list -->
    <div v-else-if="editingJob" class="summary-scroll">
      <div class="summary-header">
        <h3>Job Details</h3>
        <p>Viewing job from your list</p>
      </div>
      <div class="summary-card">
        <div class="card-header">
          <div class="card-icon" style="background: #E8F4FD; color: #246BFD">
            <Briefcase :size="18" />
          </div>
          <span class="card-title">JOB TITLE</span>
          <button class="edit-btn" @click="goEdit" aria-label="Back to list">
            <Pencil :size="14" />
          </button>
        </div>
        <div class="card-value">{{ editingJob.job_title || notProvided }}</div>
      </div>
      <div class="summary-card">
        <div class="card-header">
          <div class="card-icon" style="background: #E8F8F0; color: #10B981">
            <MapPin :size="18" />
          </div>
          <span class="card-title">LOCATION</span>
        </div>
        <div class="card-value">{{ editingJob.job_location || notProvided }}</div>
      </div>
      <div class="summary-card">
        <div class="card-header">
          <div class="card-icon" style="background: #FEF3E8; color: #F59E0B">
            <IndianRupee :size="18" />
          </div>
          <span class="card-title">SALARY</span>
        </div>
        <div class="card-value">{{ editingJob.Salary_Range || notProvided }}</div>
      </div>
      <div class="summary-card">
        <div class="card-header">
          <div class="card-icon" style="background: #EBF4FF; color: #3B82F6">
            <Users :size="18" />
          </div>
          <span class="card-title">DRIVERS REQUIRED</span>
        </div>
        <div class="card-value">{{ editingJob.number_of_drivers_required ?? notProvided }}</div>
      </div>
      <div class="summary-card">
        <div class="card-header">
          <div class="card-icon" style="background: #FDF2F8; color: #DB2777">
            <Calendar :size="18" />
          </div>
          <span class="card-title">DEADLINE</span>
        </div>
        <div class="card-value">{{ editingJob.Application_Deadline || editingJob.application_deadline || notProvided }}</div>
      </div>
      <div class="action-row">
        <button class="primary-btn secondary" @click="goBack">Back to Jobs List</button>
      </div>
    </div>

    <template v-else-if="draft">
      <div class="summary-scroll">
        <div class="summary-header">
          <h3>Review Your Job</h3>
          <p>Please review all the details before posting your job</p>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #E8F4FD; color: #246BFD">
              <Briefcase :size="18" />
            </div>
            <span class="card-title">JOB TITLE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.title || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #E8F8F0; color: #10B981">
              <MapPin :size="18" />
            </div>
            <span class="card-title">LOCATION</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.location || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #EBF4FF; color: #3B82F6">
              <Map :size="18" />
            </div>
            <span class="card-title">ROUTE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.route || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FEF3E8; color: #F59E0B">
              <Car :size="18" />
            </div>
            <span class="card-title">VEHICLE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.vehicleType || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #F3E8FF; color: #8B5CF6">
              <Clock :size="18" />
            </div>
            <span class="card-title">EXPERIENCE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.experience || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #E8FDF0; color: #059669">
              <IndianRupee :size="18" />
            </div>
            <span class="card-title">FIXED SALARY</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ salaryDisplay }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #F0F9FF; color: #0EA5E9">
              <Shield :size="18" />
            </div>
            <span class="card-title">ESI/PF</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">
            {{ draft.hasEsiPf === true ? 'Yes' : draft.hasEsiPf === false ? 'No' : notProvided }}
          </div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FEF3E2; color: #F59E0B">
              <Utensils :size="18" />
            </div>
            <span class="card-title">FOOD ALLOWANCE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ getYesNoValue(draft.hasFoodAllowance, draft.foodAllowanceAmount) }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #F0FDF4; color: #16A34A">
              <Gift :size="18" />
            </div>
            <span class="card-title">TRIP INCENTIVE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ getYesNoValue(draft.hasTripIncentive, draft.tripIncentiveAmount) }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #EEF2FF; color: #6366F1">
              <Home :size="18" />
            </div>
            <span class="card-title">ACCOMMODATION FACILITY</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">
            {{ draft.hasAccommodation === true ? 'Yes' : draft.hasAccommodation === false ? 'No' : notProvided }}
          </div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #F0F9FF; color: #0EA5E9">
              <Gauge :size="18" />
            </div>
            <span class="card-title">MILEAGE REQUIRED</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ getYesNoValueMileage(draft.hasMileage, draft.mileageValue) }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FEF3E2; color: #F59E0B">
              <CreditCard :size="18" />
            </div>
            <span class="card-title">FASTAG/ROAD KHARCHA</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ getYesNoValue(draft.hasFastag, draft.fastagAmount, '') }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FEE8E8; color: #EF4444">
              <CreditCard :size="18" />
            </div>
            <span class="card-title">LICENSE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.license || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #E8F0FE; color: #3B82F6">
              <Users :size="18" />
            </div>
            <span class="card-title">DRIVERS</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.numberOfDrivers || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FFF3E8; color: #F97316">
              <Calendar :size="18" />
            </div>
            <span class="card-title">APPLICATION DEADLINE</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ deadlineDisplay }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #E8F4FD; color: #246BFD">
              <Wrench :size="18" />
            </div>
            <span class="card-title">PREFERRED SKILLS</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value skills-row">
            <span v-for="s in draft.skills" :key="s" class="skill-chip">{{ s }}</span>
            <span v-if="!draft.skills?.length">{{ notProvided }}</span>
          </div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #F3E8FF; color: #8B5CF6">
              <FileText :size="18" />
            </div>
            <span class="card-title">JOB DESCRIPTION</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value card-desc">{{ draft.description || notProvided }}</div>
        </div>

        <div class="summary-card">
          <div class="card-header">
            <div class="card-icon" style="background: #FEF3E2; color: #F59E0B">
              <Wrench :size="18" />
            </div>
            <span class="card-title">TRUCK CONDITION</span>
            <button class="edit-btn" @click="goEdit" aria-label="Edit">
              <Pencil :size="14" />
            </button>
          </div>
          <div class="card-value">{{ draft.truckCondition || notProvided }}</div>
        </div>

        <div class="summary-actions">
          <button type="button" class="btn-secondary" @click="goEdit">Edit</button>
          <button type="button" class="submit-btn" :disabled="submitting" @click="submitJob">
            {{ submitting ? 'Posting...' : 'Post Job' }}
          </button>
        </div>
      </div>
    </template>

    <JobPremiumModal
      :visible="jobPremiumVisible"
      :job-id="postedJobId"
      :driver-count="parseInt(draft?.numberOfDrivers || '1') || 1"
      :user="user"
      @close="jobPremiumVisible = false"
      @success="onJobPremiumSuccess"
      @skip="onJobPremiumSkip"
    />
  </div>
</template>

<style scoped>
.job-summary-wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #F8F9FA;
}
.dash-header-area {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: #fff;
  border-bottom: 1px solid #E9ECEF;
}
.back-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  background: none;
  border: none;
  font-size: 15px;
  color: #246BFD;
  cursor: pointer;
  padding: 6px 0;
}
.page-title-row {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.page-title {
  font-size: 18px;
  font-weight: 700;
  color: #212529;
}
.page-subtitle {
  font-size: 13px;
  color: #6C757D;
}
.success-block {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 16px;
  padding: 24px;
}
.success-block h2 {
  font-size: 20px;
  font-weight: 700;
  color: #10b981;
}
.success-block p {
  font-size: 14px;
  color: #6b7280;
}
.summary-scroll {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}
.summary-header {
  margin-bottom: 20px;
}
.summary-header h3 {
  font-size: 18px;
  font-weight: 700;
  color: #212529;
  margin-bottom: 6px;
}
.summary-header p {
  font-size: 13px;
  color: #6C757D;
  line-height: 20px;
}
.summary-card {
  background: #fff;
  border-radius: 14px;
  padding: 16px;
  margin-bottom: 12px;
  border: 1px solid #E9ECEF;
  box-shadow: 0 2px 4px rgba(0,0,0,0.06);
}
.card-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 10px;
}
.card-icon {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.card-title {
  flex: 1;
  font-size: 11px;
  font-weight: 600;
  color: #6C757D;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.edit-btn {
  width: 28px;
  height: 28px;
  border-radius: 14px;
  background: #F0F7FF;
  border: none;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #246BFD;
  cursor: pointer;
}
.edit-btn:hover {
  background: #D0E7FF;
}
.card-value {
  font-size: 15px;
  font-weight: 600;
  color: #212529;
  margin-left: 48px;
  line-height: 22px;
}
.card-desc {
  font-size: 14px;
  font-weight: 400;
  color: #495057;
  line-height: 22px;
}
.skills-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
.skill-chip {
  background: #F0F5FF;
  color: #246BFD;
  padding: 6px 12px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 500;
}
.summary-actions {
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  margin-top: 24px;
  padding-bottom: 24px;
}
.btn-secondary {
  padding: 12px 24px;
  border-radius: 10px;
  font-weight: 600;
  background: #fff;
  border: 1px solid #e5e7eb;
  color: #6b7280;
  cursor: pointer;
}
.submit-btn {
  padding: 12px 24px;
  border-radius: 10px;
  font-weight: 600;
  background: #246BFD;
  border: none;
  color: #fff;
  cursor: pointer;
}
.submit-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// src/views/main/job-summary/index.tsx
import React, { useCallback, useMemo, memo } from 'react';
import {
    View,
    Text,
    TouchableOpacity,
    StyleSheet,
    ScrollView,
    StatusBar,
    Image,
    Pressable,
} from 'react-native';
import { useStatusBarStyle } from '@truckmitr/src/app/hooks';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { NavigatorParams, STACKS } from '@truckmitr/stacks/stacks';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useSelector } from 'react-redux';
import { useTranslation } from 'react-i18next';
import Ionicons from 'react-native-vector-icons/Ionicons';
import moment from 'moment';
import { hitSlop } from '@truckmitr/src/app/functions';

type NavigatorProp = NativeStackNavigationProp<NavigatorParams, keyof NavigatorParams>;

// Truck Images
const TruckImages = {
    cargoOpen: require('@truckmitr/src/assets/trucks/open_cargo.png'),
    cargoClosed: require('@truckmitr/src/assets/trucks/close_cargo.png'),
    tipper: require('@truckmitr/src/assets/trucks/tripper.png'),
    trailer: require('@truckmitr/src/assets/trucks/tailer.png'),
    tanker: require('@truckmitr/src/assets/trucks/tainkers.png'),
    carCarrier: require('@truckmitr/src/assets/trucks/car_carrier.png'),
    container: require('@truckmitr/src/assets/trucks/container.png'),
    reefer: require('@truckmitr/src/assets/trucks/refregerator.png'),
};

// Data Arrays - moved outside component to prevent recreation
const vehicleTypes = [
    { label: 'Cargo Truck (Open)', value: 'Cargo Truck (Open)', image: TruckImages.cargoOpen },
    { label: 'Cargo Truck (Closed)', value: 'Cargo Truck (Closed)', image: TruckImages.cargoClosed },
    { label: 'Tipper Trucks', value: 'Tipper Trucks', image: TruckImages.tipper },
    { label: 'Trailer / Semi-Trailer', value: 'Trailer / Semi-Trailer Trucks', image: TruckImages.trailer },
    { label: 'Tankers', value: 'Tankers', image: TruckImages.tanker },
    { label: 'Car Carriers', value: 'Car Carriers', image: TruckImages.carCarrier },
    { label: 'Container Trucks', value: 'Container Trucks', image: TruckImages.container },
    { label: 'Reefer Trucks', value: 'Refrigerator (Reefer) Trucks', image: TruckImages.reefer },
];

const drivingExperienceArray = [
    { labelKey: 'exp1to5Years', label: '1-5 years', value: '1-5' },
    { labelKey: 'exp5to10Years', label: '5-10 years', value: '5-10' },
    { labelKey: 'exp10to15Years', label: '10-15 years', value: '10-15' },
    { labelKey: 'exp15to20Years', label: '15-20 years', value: '15-20' },
    { labelKey: 'exp20PlusYears', label: '20+ years', value: '20+' },
];

const salaryRanges = [
    { label: '₹20,000 - 25,000', value: '20000-25000' },
    { label: '₹25,000 - 30,000', value: '25000-30000' },
    { label: '₹30,000 - 35,000', value: '30000-35000' },
    { label: '₹35,000 - 40,000', value: '35000-40000' },
    { label: '₹40,000 - 50,000', value: '40000-50000' },
    { label: '₹50,000+', value: '50000+' },
];

const licenseTypes = [
    { label: 'LMV (Light)', value: 'LMV', emoji: '🚗' },
    { label: 'HMV (Heavy)', value: 'HMV', emoji: '🚛' },
    { label: 'HGMV (Goods)', value: 'HGMV', emoji: '📦' },
    { label: 'HPMV/HTV', value: 'HPMV/HTV', emoji: '🚚' },
];

const operationalSegments = [
    { id: 'ecommerce', label: 'E-commerce', emoji: '📦' },
    { id: 'white_goods', label: 'White Goods', emoji: '🏠' },
    { id: 'livestock', label: 'Livestock', emoji: '🐄' },
    { id: 'perishable', label: 'Perishable', emoji: '🍎' },
    { id: 'oversized', label: 'Oversized', emoji: '📏' },
    { id: 'fuel_tanker', label: 'Fuel Tanker', emoji: '⛽' },
    { id: 'automobile', label: 'Automobile Carrier', emoji: '🚗' },
    { id: 'construction', label: 'Construction', emoji: '🏗️' },
    { id: 'refrigerator', label: 'Refrigerator Vehicle', emoji: '❄️' },
    { id: 'others', label: 'Others', emoji: '📋' },
];

const conditionLabelsMap: { [key: string]: string } = {
    'excellent': 'Excellent (New/Very well maintained)',
    'good': 'Good (Regularly serviced)',
    'average': 'Average (Working condition)',
    'old_running': 'Old but Running',
    'road_ready': 'Made Road Ready after joining'
};

// Memoized Edit Button Component for better performance
const EditButton = memo(({ onPress }: { onPress: () => void }) => (
    <Pressable
        onPress={onPress}
        style={({ pressed }) => [styles.editButton, pressed && styles.editButtonPressed]}
        hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
    >
        <Ionicons name="pencil" size={14} color="#246BFD" />
    </Pressable>
));

// Memoized Summary Card Component
const SummaryCard = memo(({ iconBg, iconName, iconColor, title, value, onEdit, children }: {
    iconBg: string; iconName: string; iconColor: string; title: string; value?: string; onEdit: () => void; children?: React.ReactNode;
}) => (
    <View style={styles.summaryCard}>
        <View style={styles.summaryCardHeader}>
            <View style={[styles.summaryIconContainer, { backgroundColor: iconBg }]}>
                <Ionicons name={iconName as any} size={18} color={iconColor} />
            </View>
            <Text style={styles.summaryCardTitle}>{title}</Text>
            <EditButton onPress={onEdit} />
        </View>
        {children || <Text style={styles.summaryCardValue}>{value}</Text>}
    </View>
));

export default function JobSummary() {
    const { t } = useTranslation();
    useStatusBarStyle('dark-content');
    const safeAreaInsets = useSafeAreaInsets();
    const navigation = useNavigation<NavigatorProp>();
    const { addJob } = useSelector((state: any) => state?.job);

    const notProvided = useMemo(() => t('notProvided') || 'Not Provided', [t]);

    const getSalaryLabel = useCallback((value: string) => {
        return salaryRanges.find(s => s.value === value)?.label || value || notProvided;
    }, [notProvided]);

    const getExperienceLabel = useCallback((value: string) => {
        const exp = drivingExperienceArray.find(e => e.value === value);
        return exp ? (t(exp.labelKey) || exp.label) : (value || notProvided);
    }, [t, notProvided]);

    const getLicenseLabel = useCallback((value: string) => {
        return licenseTypes.find(l => l.value === value)?.label || value || notProvided;
    }, [notProvided]);

    const getVehicleImage = useCallback((value: string) => {
        return vehicleTypes.find(v => v.value === value)?.image || null;
    }, []);

    const handleEdit = useCallback((stepId: string) => {
        navigation.navigate(STACKS?.EDIT_JOB, { stepId });
    }, [navigation]);

    const goBack = useCallback(() => navigation.goBack(), [navigation]);

    // Memoized edit handlers
    const editJobTitle = useCallback(() => handleEdit('job_title'), [handleEdit]);
    const editLocation = useCallback(() => handleEdit('job_location'), [handleEdit]);
    const editRoute = useCallback(() => handleEdit('route'), [handleEdit]);
    const editVehicle = useCallback(() => handleEdit('vehicle_type'), [handleEdit]);
    const editExperience = useCallback(() => handleEdit('experience'), [handleEdit]);
    const editSalary = useCallback(() => handleEdit('salary_range'), [handleEdit]);
    const editEsiPf = useCallback(() => handleEdit('esi_pf'), [handleEdit]);
    const editFoodAllowance = useCallback(() => handleEdit('food_allowance'), [handleEdit]);
    const editTripIncentive = useCallback(() => handleEdit('trip_incentive'), [handleEdit]);
    const editAccommodation = useCallback(() => handleEdit('accommodation'), [handleEdit]);
    const editMileage = useCallback(() => handleEdit('mileage'), [handleEdit]);
    const editFastag = useCallback(() => handleEdit('fastag'), [handleEdit]);
    const editLicense = useCallback(() => handleEdit('license_type'), [handleEdit]);
    const editDriversCount = useCallback(() => handleEdit('drivers_count'), [handleEdit]);
    const editDeadline = useCallback(() => handleEdit('deadline'), [handleEdit]);
    const editSkills = useCallback(() => handleEdit('preferred_skills'), [handleEdit]);
    const editDescription = useCallback(() => handleEdit('job_description'), [handleEdit]);
    const editTruckCondition = useCallback(() => handleEdit('truck_condition'), [handleEdit]);

    // Memoized values
    const yesText = useMemo(() => t('yes') || 'Yes', [t]);
    const noText = useMemo(() => t('no') || 'No', [t]);

    const getYesNoValue = useCallback((value: string | undefined, desc?: string, suffix?: string) => {
        if (value === 'yes') return `${yesText}${desc ? ` - ${suffix === 'km/l' ? desc : '₹' + desc}${suffix || '/day'}` : ''}`;
        if (value === 'no') return noText;
        return notProvided;
    }, [yesText, noText, notProvided]);

    const truckConditionValue = useMemo(() => {
        if (!addJob?.truck_condition) return notProvided;
        return t(addJob.truck_condition) || conditionLabelsMap[addJob.truck_condition] || addJob.truck_condition;
    }, [addJob?.truck_condition, t, notProvided]);

    const deadlineValue = useMemo(() => {
        return addJob?.Application_Deadline ? moment(addJob.Application_Deadline).format('DD MMMM YYYY') : notProvided;
    }, [addJob?.Application_Deadline, notProvided]);

    return (
        <View style={[styles.container, { paddingTop: safeAreaInsets.top }]}>
            <StatusBar barStyle="dark-content" backgroundColor="#F8F9FA" />

            {/* Header */}
            <View style={styles.header}>
                <Pressable
                    onPress={goBack}
                    style={styles.backButton}
                    hitSlop={hitSlop(10)}
                >
                    <Ionicons name="chevron-back" size={22} color="#246BFD" />
                </Pressable>
                <Text style={styles.headerTitle}>{t('jobSummary') || 'Job Summary'}</Text>
                <View style={{ width: 36 }} />
            </View>

            <ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false} removeClippedSubviews>
                {/* Header Section */}
                <View style={styles.summaryHeader}>
                    <Text style={styles.summaryHeaderTitle}>{t('reviewYourJob') || 'Review Your Job'}</Text>
                    <Text style={styles.summaryHeaderSubtitle}>{t('reviewJobDetailsMessage') || 'Please review all the details before posting your job'}</Text>
                </View>

                <SummaryCard iconBg="#E8F4FD" iconName="briefcase" iconColor="#246BFD" title={t('jobTitle') || 'Job Title'} value={addJob?.job_title || notProvided} onEdit={editJobTitle} />
                <SummaryCard iconBg="#E8F8F0" iconName="location" iconColor="#10B981" title={t('location') || 'Location'} value={addJob?.job_location || notProvided} onEdit={editLocation} />
                <SummaryCard iconBg="#EBF4FF" iconName="map" iconColor="#3B82F6" title={t('route') || 'Route'} value={addJob?.route || notProvided} onEdit={editRoute} />

                {/* Vehicle Card */}
                <SummaryCard iconBg="#FEF3E8" iconName="car" iconColor="#F59E0B" title={t('vehicle') || 'Vehicle'} onEdit={editVehicle}>
                    {getVehicleImage(addJob?.vehicle_type) && (
                        <Image source={getVehicleImage(addJob?.vehicle_type)} style={styles.summaryVehicleImage} resizeMode="contain" />
                    )}
                    <Text style={[styles.summaryCardValue, { fontSize: 13, marginTop: 4 }]}>{addJob?.vehicle_type || notProvided}</Text>
                </SummaryCard>

                <SummaryCard iconBg="#F3E8FF" iconName="time" iconColor="#8B5CF6" title={t('experience') || 'Experience'} value={getExperienceLabel(addJob?.Required_Experience)} onEdit={editExperience} />
                <SummaryCard iconBg="#E8FDF0" iconName="cash" iconColor="#059669" title={t('fixedSalary') || 'Fixed Salary'} value={getSalaryLabel(addJob?.Salary_Range)} onEdit={editSalary} />
                <SummaryCard iconBg="#F0F9FF" iconName="shield-checkmark" iconColor="#0EA5E9" title={t('esiPf') || 'ESI/PF'} value={addJob?.esi_pf === 'yes' ? yesText : addJob?.esi_pf === 'no' ? noText : notProvided} onEdit={editEsiPf} />
                <SummaryCard iconBg="#FEF3E2" iconName="restaurant" iconColor="#F59E0B" title={t('foodAllowance') || 'Food Allowance'} value={getYesNoValue(addJob?.food_allowance, addJob?.food_allowance_desc)} onEdit={editFoodAllowance} />
                <SummaryCard iconBg="#F0FDF4" iconName="gift" iconColor="#16A34A" title={t('tripIncentive') || 'Trip Incentive'} value={getYesNoValue(addJob?.trip_incentive, addJob?.trip_incentive_desc)} onEdit={editTripIncentive} />
                <SummaryCard iconBg="#EEF2FF" iconName="home" iconColor="#6366F1" title={t('accommodationFacility') || 'Accommodation Facility'} value={addJob?.rahane_ki_suvidha === 'yes' ? yesText : addJob?.rahane_ki_suvidha === 'no' ? noText : notProvided} onEdit={editAccommodation} />
                <SummaryCard iconBg="#F0F9FF" iconName="speedometer" iconColor="#0EA5E9" title={t('mileageRequired') || 'Mileage Required'} value={getYesNoValue(addJob?.mileage, addJob?.mileage_desc, 'km/l')} onEdit={editMileage} />
                <SummaryCard iconBg="#FEF3E2" iconName="card" iconColor="#F59E0B" title={t('fastagRoadKharcha') || 'FASTag/Road Kharcha'} value={getYesNoValue(addJob?.fast_tag_road_kharcha, addJob?.fast_tag_road_kharcha_desc, '')} onEdit={editFastag} />
                <SummaryCard iconBg="#FEE8E8" iconName="card" iconColor="#EF4444" title={t('license') || 'License'} value={getLicenseLabel(addJob?.Type_of_License)} onEdit={editLicense} />
                <SummaryCard iconBg="#E8F0FE" iconName="people" iconColor="#3B82F6" title={t('drivers') || 'Drivers'} value={addJob?.Job_Management || notProvided} onEdit={editDriversCount} />
                <SummaryCard iconBg="#FFF3E8" iconName="calendar" iconColor="#F97316" title={t('applicationDeadline') || 'Application Deadline'} value={deadlineValue} onEdit={editDeadline} />

                {/* Skills Card */}
                <SummaryCard iconBg="#E8F4FD" iconName="construct" iconColor="#246BFD" title={t('preferredSkills') || 'Preferred Skills'} onEdit={editSkills}>
                    <View style={styles.summarySkillsContainer}>
                        {(addJob?.Preferred_Skills || []).map((skill: string, index: number) => {
                            const skillData = operationalSegments.find(s => s.label === skill);
                            return (
                                <View key={index} style={styles.summarySkillChip}>
                                    <Text style={{ fontSize: 12 }}>{skillData?.emoji || '📋'}</Text>
                                    <Text style={styles.summarySkillText}>{skill}</Text>
                                </View>
                            );
                        })}
                        {(!addJob?.Preferred_Skills || addJob.Preferred_Skills.length === 0) && (
                            <Text style={styles.summaryCardValue}>{notProvided}</Text>
                        )}
                    </View>
                </SummaryCard>

                <SummaryCard iconBg="#F3E8FF" iconName="document-text" iconColor="#8B5CF6" title={t('jobDescriptionTitle') || 'Job Description'} onEdit={editDescription}>
                    <Text style={[styles.summaryCardValue, styles.summaryDescription]}>{addJob?.Job_Description || notProvided}</Text>
                </SummaryCard>

                <SummaryCard iconBg="#FEF3E2" iconName="build" iconColor="#F59E0B" title={t('truckCondition') || 'Truck Condition'} value={truckConditionValue} onEdit={editTruckCondition} />

                <View style={{ height: 30 }} />
            </ScrollView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8F9FA' },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E9ECEF' },
    backButton: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.05)' },
    headerTitle: { fontSize: 18, fontWeight: '700', color: '#212529' },
    scrollView: { flex: 1 },
    scrollContent: { padding: 16 },
    summaryHeader: { marginBottom: 20 },
    summaryHeaderTitle: { fontSize: 18, fontWeight: '700', color: '#212529', marginBottom: 6 },
    summaryHeaderSubtitle: { fontSize: 13, color: '#6C757D', lineHeight: 20 },
    summaryCard: { backgroundColor: 'white', borderRadius: 14, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#E9ECEF', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
    summaryCardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    summaryIconContainer: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    summaryCardTitle: { fontSize: 11, fontWeight: '600', color: '#6C757D', textTransform: 'uppercase', letterSpacing: 0.5, flex: 1 },
    summaryCardValue: { fontSize: 15, fontWeight: '600', color: '#212529', marginLeft: 48, lineHeight: 22 },
    summaryVehicleImage: { width: '100%', height: 60, marginTop: 4, marginBottom: 4 },
    summarySkillsContainer: { flexDirection: 'row', flexWrap: 'wrap', marginLeft: 48, marginTop: 0 },
    summarySkillChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F0F5FF', borderRadius: 20, paddingVertical: 6, paddingHorizontal: 12, marginRight: 8, marginBottom: 8 },
    summarySkillText: { fontSize: 12, color: '#246BFD', fontWeight: '500', marginLeft: 5 },
    summaryDescription: { fontSize: 14, lineHeight: 22, color: '#495057', fontWeight: '400' },
    editButton: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F0F7FF', justifyContent: 'center', alignItems: 'center' },
    editButtonPressed: { opacity: 0.6, backgroundColor: '#D0E7FF' },
});
